name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Initialize repository if it doesn't exist
            if [ ! -d "/app/.git" ]; then
              cd /app
              rm -rf *
              git init
              git remote add origin https://github.com/mz-0-1/03-human-review-async.git
              git fetch
              git checkout -f main
            else
              cd /app
              git fetch
              git reset --hard origin/main
            fi
            
            # Now run docker compose
            docker-compose down
            docker-compose up -d --build